### ISSUE TITLE
Failed to run your demo

### ISSUE THREAD

**Issue by antelidakis** [alexfjw/jp-ocr-prunned-cnn#1] opened 2019-01-25 13:34 UTC
Hi Alex, thank you so much for sharing a worked example of NN pruning - much appreciated! 
I am trying to execute your code and I am facing run-time errors. 

Originally I spotted a bug on the constructor of the  VGG network that you need to fix.
In "jp-ocr-prunned-cnn/blob/master/src/nn/models.py", line 68 you need to correct the indetation with one less tab in as the existing one causes an early exit of the loop and the "features" part of the CNN are incomplete.

Once this is fixed, I am getting out of memory errors when using the command:
python -m src.main --train --model vgg11_bn --dataset etl2

Can you share your hardware setup that run this experiment?

**Comment by alexfjw** [comment] 2019-01-25 13:43
Hi there, pruning itself takes a lot of memory, iirc some magnitudes more than the usual required for back propagation. The vgg model itself too requires a lot of memory and I didn't manage to run it successfully either on my meager gtx1060 6gb. The issue lies with storing all that additional data to determine which neurons to prune. The code is almost a 1-1 duplicate of chinesenet though, so it should have worked given enough memory. Hope this helps.

**Comment by antelidakis** [comment] 2019-01-25 14:01
Thank you very much for the inside info! I will attempt to run it on a AWS EC2 instance now that I know, once I find time, and come back to you. -Antonis

**Closed as completed** 2019-06-13 03:33 UTC
